export type BackendModuleImageTuple = [string, string];

export type BackendModuleType = {
  id: number | string;
  name: string;
  createdAt?: string;
  updatedAt?: string;
};

export type BackendModule = {
  id: number | string;
  moduleBuildingId?: string | null;
  name: string;
  description?: string | null;
  fileName?: string | null;
  glbFile?: string | null;
  moduleImage?: string | null;
  images?: BackendModuleImageTuple[];
  noOfBedrooms?: number | string | null;
  noOfBathrooms?: number | string | null;
  size?: number | string | null;
  width?: number | string | null;
  length?: number | string | null;
  height?: number | string | null;
  price?: number | string | null;
  pricePerSqft?: number | string | null;
  quantity?: number | string | null;
  unitType?: string | null;
  status?: string | null;
  moduleTypeId?: number | string | null;
  moduleType?: BackendModuleType | null;
  subModuleTypeId?: number | string | null;
  subModuleType?: BackendModuleType | null;
  suggestedUse?: string | null;
  designedBy?: string | null;
  areaObj?: Record<string, string | number | null> | null;
  includes?: unknown;
  optionalFeatures?: unknown;
  keyWords?: unknown[];
  amenities?: unknown[];
  amenitiesTables?: unknown[];
  upgradesType?: unknown[];
  kitchenLayoutId?: number | string | null;
  bathroomLayoutId?: number | string | null;
  kitchenLayout?: unknown;
  bathroomLayout?: unknown;
  bathLayout?: unknown;
  efficient?: boolean | null;
  isPremium?: boolean | null;
  isSuperAdmin?: boolean | null;
  createdAt?: string;
  updatedAt?: string;
  deletedAt?: string | null;
  userId?: string | null;
};
